# Generated by Django 4.2 on 2025-06-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('normal', 'Normal'), ('fighting', 'Lucha'), ('flying', 'Volador'), ('poison', 'Veneno'), ('ground', 'Tierra'), ('rock', 'Roca'), ('bug', 'Bicho'), ('ghost', 'Fantasma'), ('steel', 'Acero'), ('fire', 'Fuego'), ('water', 'Agua'), ('grass', 'Planta'), ('electric', 'Eléctrico'), ('psychic', 'Psíquico'), ('ice', 'Hielo'), ('dragon', 'Dragón'), ('dark', 'Siniestro'), ('fairy', 'Hada')], max_length=100, verbose_name='Tipo')),
                ('weight', models.FloatField(help_text='en kg', verbose_name='Peso')),
                ('height', models.FloatField(help_text='en m', verbose_name='Altura')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pokemon_images/', verbose_name='Fotografía')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.trainer')),
            ],
        ),
    ]
